---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/walexee/spring_sample_config_values # default
          #username: abc
          #password: abc
          search-paths:
            - 'app*'
#          repos:
#            local:
#              pattern: '*/local'
#              uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-local # alt
#              search-paths:
#                - 'station*'
#security:
#  basic:
#    enabled: true
#  user:
#    name: pluralsight
#    password: pluralsight